#
# Handlers for nomad
#
# @see http://docs.ansible.com/playbooks_intro.html#handlers-running-operations-on-change
#
# Notes:
#  "Notify handlers are always run in the order written."
#  These use sudo since deploys are commonly performed without sudo
#
---

- name: Reload nomad
  become: yes
  command: pkill -HUP nomad

- name: Restart nomad
  service:
    name: nomad
    state: restarted
